### ISSUE TITLE
Add s390x support to the operator

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/operator#107]
In the CoCo 0.1 release notes it states: 'S390x is not supported by the CoCo operator'. It would be great to be able to remove that.

I think there are at least a couple of things that need doing here:
- Getting the [`sudo make cc-payload`](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-generate-a-kata-containers-payload-for-the-confidential-containers-operator.md) process to create an `s390x` payload image.
  - Given that we don't currently have GHA runners for s390x I think we might need to use cross compilation to produce the s390x image. I'm not sure if this was this approach that Jakob had running at the start of the year, or if he built it on a z box?
  - Does Quay support multi-arch manifest images. If so we should be able to push the amd64 and s390x payload images and create the multi-arch manifest as part of the payload image, which would save some headaches having to create separate ccruntime in the operator for each architecture.
  - We should probably consider moving this portion of the work into kata-containers and then making this depend on it?
- Updating any operator specific code to support multi-arch
  - I'm not sure what if anything is involved here, but it will depend on the above

**Comment by stevenhorsman** [comment]
Hey @BbolroC - I think this has been closed by your work in https://github.com/confidential-containers/operator/pull/137, is that correct?

**Comment by BbolroC** [comment]
> * Getting the [`sudo make cc-payload`](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-generate-a-kata-containers-payload-for-the-confidential-containers-operator.md) process to create an `s390x` payload image.

ATM, we can build a payload image for s390x only via GHA workflows ([cc-payload-s390x.yaml](https://github.com/kata-containers/kata-containers/blob/CCv0/.github/workflows/cc-payload-s390x.yaml) and [cc-payload-after-push-s390x.yaml](https://github.com/kata-containers/kata-containers/blob/CCv0/.github/workflows/cc-payload-after-push-s390x.yaml)) With `make cc-payload`, we would get a build failure because it tries to build a [full package](https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/kata-deploy/local-build/Makefile#L85) for x86_64. I will raise an issue for this. Thanks.
  
>   * Given that we don't currently have GHA runners for s390x I think we might need to use cross compilation to produce the s390x image. I'm not sure if this was this approach that Jakob had running at the start of the year, or if he built it on a z box?

A machine on Marist Cloud is added as a GHA runner for s390x to the repo `kata-containers`. We can use it by `runs-on: s390x` in a workflow.

>   * Does Quay support multi-arch manifest images. If so we should be able to push the amd64 and s390x payload images and create the multi-arch manifest as part of the payload image, which would save some headaches having to create separate ccruntime in the operator for each architecture.

Finally, it does. The operator for s390x uses `quay.io/confidential-containers/runtime-payload-ci:kata-containers-latest` in the [e2e test](https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/s390x/kustomization.yaml#L12). I believe `quay.io/confidential-containers/runtime-payload:kata-containers-latest` will be available for the upcoming release thanks to the GHA [workflow config](https://github.com/kata-containers/kata-containers/blob/CCv0/.github/workflows/cc-payload.yaml#L36).

>   * We should probably consider moving this portion of the work into kata-containers and then making this depend on it?

Most things (other than `make cc-payload`) have been finished, but they miss a reference to this issue. Sorry. 

> * Updating any operator specific code to support multi-arch

Done by https://github.com/confidential-containers/operator/pull/137 (plus, e2e test: https://github.com/confidential-containers/operator/pull/142)

I hope the answers would meet your expectation. Thank you for letting me know `make cc-payload`. :wink:

**Comment by stevenhorsman** [comment]
Given that the outstanding piece of work from this list that been raised now in kata, I think we can close this. Thanks Choi!
