### ISSUE TITLE
Change container engine binary via the operator

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/operator#25]
This issue is to track the work required to deploy and enable container runtime (eg. containerd) required for confidential containers

**Comment by fidencio** [comment]
In order to kick this off, let's start by defining what are the **host** OSes we're targeting,

We need to do so in order to define what's oldest glibc we're building against, so the container engine runtime can actually run on the node used.
I'd suggest using something like CentOS 7 for that.  @bpradipt, @jensfr, any objection?

**Comment by bpradipt** [comment]
> In order to kick this off, let's start by defining what are the **host** OSes we're targeting,
> 
> We need to do so in order to define what's oldest glibc we're building against, so the container engine runtime can actually run on the node used. I'd suggest using something like CentOS 7 for that. @bpradipt, @jensfr, any objection?

@fidencio fine with me

**Comment by fidencio** [comment]
@jensfr, @bpradipt, I am closing this one considering it's done in https://github.com/fidencio/container-engine-for-cc-payload and the daemonset image can be found at https://quay.io/repository/confidential-containers/container-engine-for-cc-payload?tab=tags.

Please, let feel free to re-open in case you think something is missing, but if any bug is found, please, open an issue for it in https://github.com/fidencio/container-engine-for-cc-payload
