### ISSUE TITLE
COCO first release: Publishing the CC operator via operator hub

### ISSUE THREAD

**Issue by ariel-adam** [confidential-containers/operator#46]
We heed to publish the CC operator in operator hub.
Small effort and mainly procedure .

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jensfr** [comment]
I discussed this with Pradipta and Fabiano and we were not sure if it is a good idea to publish it in Operatorhub just now. The reason is that users may expect it to be a stable product. But we are still doing things like replacing the containerd binary on the nodes, which is not considered to be the final solution. 

We can either publish it in Operatorhub anyway and mark it as *alpha* or we defer it to the next release. What do people think?

**Comment by bpradipt** [comment]
We discussed and concluded in the community call to publish the operator in the OperatorHub.

Instructions - https://operatorhub.io/contribute

**Comment by bpradipt** [comment]
@jensfr submitted the PR to kickstart the publishing process - https://github.com/k8s-operatorhub/community-operators/pull/1764

**Comment by jensfr** [comment]
The PR was merged  https://github.com/k8s-operatorhub/community-operators/pull/1764

**Comment by bpradipt** [comment]
Great work @jensfr 
Here is a screenshot from operatorhub.io

![image](https://user-images.githubusercontent.com/9287071/192461961-9c67e197-0f17-4ff8-b380-8d5ac94405e2.png)
