### ISSUE TITLE
CI: add job for kata-clh runtimeclass

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/operator#90]
We should use the same non-TEE tests as in the kata-qemu jobs.

**Comment by arronwy** [comment]
I also found some other errors, will give more updates after debugging

**Comment by arronwy** [comment]
Hi @wainersm `kata-clh-tdx` runtime tests cases passed on my machine with some changes, I found the root cause for other runtime failed to work is due to we update the default kata config file instead of the `RUNTIMECLASS` kata config file in tests scripts.

After operator is installed, the default runtime will be `kata-qemu` and `/opt/confidential-containers/share/defaults/kata-containers/configuration.toml` will link to `/opt/confidential-containers/share/defaults/kata-containers/configuration-qemu.toml` with `RUNTIMECLASS` environment, test workload can launch with the right runtime, but the tests scripts will use `kata-runtime kata-env` to update the config for testing like update kernel param for agent config and copy signature/decrypt keys to the righ rootfs image.  Then the `set_kata_config` in your previous PR is still needed for our CI testing:
https://github.com/confidential-containers/operator/commit/5c3ed60663383c1fba6849cebed0581f7f0baf8f

or we can use sed to update the config in tests scripts like:
```
sed -i "s#kata-runtime kata-env#kata-runtime --config $runtime_config_file kata-env#g" ../../../lib/common.bash
```

**Comment by arronwy** [comment]
BTW, @stevenhorsman @wainersm during the testing for operator CI, I also found the `ssh_demo_pod` case in `agent_image_encrypted.bats` may failed duo to:
`ssh-keyscan ${pod_ip_address} 2>/dev/null` is null, the pod may be ready but ssh service is not ready yet, I added a sleep in this PR, please review: https://github.com/kata-containers/tests/pull/5145
